---
title: "Graduate Project"
subtitle: "STA 504"
author: "Joey Hastings"
output:
  rmdformats::html_clean:
    self_contained: true
    lightbox: true
    gallery: true
    thumbnails: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, fig.align = "center", fig.height = 4, fig.width = 8)
library(ggthemes)
library(httr)
library(lubridate)
library(plotly)
library(tidyverse)
```

# Download ATP data from Github

https://github.com/JeffSackmann/tennis_atp

```{r data-wrangle, eval = FALSE}
# https://stackoverflow.com/questions/25485216/how-to-get-list-files-from-a-github-repository-folder-using-r
req <- GET("https://api.github.com/repos/JeffSackmann/tennis_atp/git/trees/master?recursive=1")
stop_for_status(req)
file_list <- unlist(lapply(content(req)$tree, "[", "path"), use.names = F)

# Source of all .csv files
github_master_url <- "https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/"

# https://stackoverflow.com/questions/11433432/how-to-import-multiple-csv-files-at-once
atp_tennis_raw_data <-
  as_tibble(file_list[str_detect(file_list, "atp_matches_([:digit:]{4}).csv")]) %>%
  mutate(file_path = paste0(github_master_url, value)) %>%
  select(file_path) %>%
  map_df( ~ read_csv(., col_type = cols(.default = "c")))

write_csv(atp_tennis_raw_data, "data/atp_matches.csv")
```

# Import all ATP data

```{r data-import}
# Common column types for .csv files of interest
c_types <-
  c(
    tourney_id    = "c",
    tourney_name  = "f",
    surface       = "f",
    draw_size     = "i",
    tourney_level = "f",
    tourney_date  = "c",
    match_num     = "c", 
    
    winner_id    = "c",
    winner_seed  = "f",
    winner_entry = "f",
    winner_name  = "c",
    winner_hand  = "f",
    winner_ht    = "d",
    winner_ioc   = "f",
    winner_age   = "d",
    
    loser_id    = "c",
    loser_seed  = "f",
    loser_entry = "f",
    loser_name  = "c",
    loser_hand  = "f",
    loser_ht    = "d",
    loser_ioc   = "f",
    loser_age   = "d",
    
    score   = "c",
    best_of = "i",
    round   = "f",
    minutes = "i",
    
    w_ace     = "i",
    w_df      = "i",
    w_svpt    = "i",
    w_1stIn   = "i",
    w_1stWon  = "i",
    w_2ndWon  = "i",
    w_SvGms   = "i",
    w_bpSaved = "i",
    w_bpFaced = "i",
    
    l_ace     = "i",
    l_df      = "i",
    l_svpt    = "i",
    l_1stIn   = "i",
    l_1stWon  = "i",
    l_2ndWon  = "i",
    l_SvGms   = "i",
    l_bpSaved = "i",
    l_bpFaced = "i",
    
    winner_rank        = "i",
    winner_rank_points = "i",
    loser_rank         = "i",
    loser_rank_points  = "i"
  )

atp_tennis <- read_csv("data/atp_matches.csv", col_types = c_types) %>%
  mutate(tourney_name = recode_factor(tourney_name,
                                      "Australian Open" = "Australian Open",
                                      "Roland Garros" = "French Open",
                                      "Wimbledon" = "Wimbledon",
                                      "Us Open" = "US Open"), 
         tourney_date = ymd(tourney_date),
         tourney_year = year(tourney_date))
```

# Process data

```{r grand-slam-data}
big_3_names <- c("Roger Federer", "Rafael Nadal", "Novak Djokovic")

gs_matches <- atp_tennis %>%
  filter(tourney_level == "G") %>%
  select(
    tourney_id,
    tourney_name,
    surface,
    tourney_date,
    tourney_year,
    winner_id,
    winner_name,
    winner_age,
    loser_id,
    loser_name,
    loser_age,
    round
  ) %>%
  
  unite(winner_id, winner_name, col = "winner", sep = ";") %>%
  unite(loser_id,  loser_name,  col = "loser",  sep = ";") %>%
  
  pivot_longer(cols = c(winner, loser),
               names_to = "outcome",
               values_to = "player") %>%
  
  separate(player,
           into = c("player_id", "player_name"),
           sep = ";") %>%
  
  mutate(player_age = if_else(outcome == "winner", winner_age, loser_age)) %>%
  
  select(-c(winner_age, loser_age)) %>%
  group_by(player_id, player_name) %>%
  arrange(tourney_date) %>%
  
  mutate(floor_age = floor(player_age),
         win = if_else(round == "F" & outcome == "winner",
                       1, 0)) %>%
  
  arrange(player_id, player_name, tourney_date) %>%
  mutate(cum_gs_wins = cumsum(win),
         total_gs_wins = sum(win),
         double_digits = if_else(total_gs_wins >= 10, TRUE, FALSE),
         big_3 = if_else(player_name %in% big_3_names,
                         TRUE, FALSE)
  )

# get names of players who have won at least 1 grand slam
gs_winners <- filter(gs_matches, win > 0) %>%
  distinct(player_id, player_name)

gs_matches_winners <- inner_join(gs_matches, gs_winners, by = c("player_id", "player_name"))

gs_total_wins <- gs_matches_winners %>%
  arrange(desc(tourney_date)) %>%
  slice_head(n = 1)

by_var <- "big_3"
```

# Plots


## GS wins by age
```{r gs-wins-age}

# by age
ggplot() +
  # not big 3
  geom_line(
    data = filter(gs_matches_winners, !(!!sym(by_var))),
    aes(x = floor_age, y = cum_gs_wins, group = player_name),
    color = "dark gray"
  ) +
  geom_point(
    data = filter(gs_total_wins, !(!!sym(by_var))),
    aes(x = floor_age, y = total_gs_wins, group = player_name),
    color = "dark gray"
  ) +
  # big 3
  geom_line(
    data = filter(gs_matches_winners, !!sym(by_var)),
    aes(
      x = floor_age,
      y = cum_gs_wins,
      color = player_name,
      group = player_name
    ),
    size = 1,
    alpha = 0.5
  ) +
  geom_point(
    data = filter(gs_total_wins, !!sym(by_var)),
    aes(
      x = floor_age,
      y = total_gs_wins,
      color = player_name,
      group = player_name
    ),
    alpha = 0.5
  ) +
  theme_few() +
  theme(legend.position = "bottom") +
  labs(color = "")
```

## GS wins by year
```{r gs-wins-year}
# by year

ggplot() +
  # category: false
  geom_line(
    data = filter(gs_matches_winners, !(!!sym(by_var))),
    aes(
      x = tourney_year,
      y = cum_gs_wins,
      group = player_name
    ),
    color = "dark gray"
  ) +
  geom_point(
    data = filter(gs_total_wins, !(!!sym(by_var))),
    aes(
      x = tourney_year,
      y = total_gs_wins,
      group = player_name
    ),
    color = "dark gray"
  ) +
  # category: true
  geom_line(
    data = filter(gs_matches_winners, !!sym(by_var)),
    aes(
      x = tourney_year,
      y = cum_gs_wins,
      color = player_name,
      group = player_name
    ),
    alpha = 0.5
  ) +
  geom_point(
    data = filter(gs_total_wins, !!sym(by_var)),
    aes(
      x = tourney_year,
      y = total_gs_wins,
      color = player_name,
      group = player_name
    ),
    alpha = 0.5
  ) +
  theme_few() +
  theme(legend.position = "bottom") +
  labs(color = "")
```

## GS wins comparison: big 3 vs. others since 2003
```{r gs-finals-2003, fig.height = 10, fig.width = 9}
# grand slam finals since 2003
gs_final_2003 <- filter(atp_tennis,
                        tourney_level == "G",
                        round == "F",
                        tourney_year >= 2003) %>%
  mutate(
    big_3 = case_when(
      winner_name == "Roger Federer" ~ "Federer",
      winner_name == "Rafael Nadal" ~ "Nadal",
      winner_name == "Novak Djokovic" ~ "Djokovic",
      TRUE ~ "Other"
    )
  )


ggplot(data = gs_final_2003) +
  geom_tile(aes(x = tourney_name, y = tourney_year, fill = big_3), color = "black") +
  geom_text(aes(x = tourney_name, y = tourney_year, label = winner_name),
            fontface = "bold") +
  scale_y_reverse(breaks = seq(2003, 2021)) +
  coord_cartesian(expand = FALSE) +
  scale_fill_manual(values = c("#5CAE1E", "#6FD123", "#66C021", "gray")) +
  theme_few() +
  theme(legend.position = "none")
```

## big 3 wins comparison by slam

```{r big-3-comparison}
gs_wins_b3 <-
  filter(gs_matches,
         round == "F",
         outcome == "winner",
         player_name %in% big_3_names) %>%
  group_by(tourney_name, player_name) %>%
  summarize(win = n(), .groups = "keep")

ggplot(data = gs_wins_b3) +
  geom_col(aes(x = player_name, y = win, fill = tourney_name), position = position_dodge2()) +
  theme_few() +
  theme(legend.position = "bottom")
```
